name: Go Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        goVersion: ["1.21", "1.22", "1.23"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVersion }}
      - name: Test with the Go CLI
        run: go test -race ./...